import { createGlobalStyle } from 'styled-components';
// import { generate } from '@ant-design/colors';
import { QueryClientProvider, QueryClient } from 'react-query';
import RouterRoot from './RouterRoot';
import 'antd/dist/antd.css';

import AuthContextProvider from './contexts/AuthContext';

// Nokia color palette generated by ant design need to modify themes
// const colors = generate('#124191');

const GlobalStyles = createGlobalStyle`
  #root {
    height: 100%;
    --primaryNokiaColor: #124191;
    --highlightColor: #e6f7ffa6;
  }
`;

const client = new QueryClient();

function App() {
  return (
    <QueryClientProvider client={client}>
      <AuthContextProvider>
        <GlobalStyles />
        <RouterRoot />
      </AuthContextProvider>
    </QueryClientProvider>
  );
}

export default App;
