import { createGlobalStyle } from 'styled-components';
// import { generate } from '@ant-design/colors';
import RouterRoot from './RouterRoot';
import 'antd/dist/antd.css';
import AdminContextProvider from './components/admin/Common/AdminContext';

// Nokia color palette generated by ant design need to modify themes
// const colors = generate('#124191');

const GlobalStyles = createGlobalStyle`
  #root {
    height: 100%;
    --primaryNokiaColor: #124191;
    --highlightColor: #e6f7ffa6;
  }
`;

function App() {
  return (
    <AdminContextProvider>
      <GlobalStyles />
      <RouterRoot />
    </AdminContextProvider>
  );
}

export default App;
