import { Thing } from '@my-garage/common';

// eslint-disable-next-line import/prefer-default-export
export const thingsArray: Thing[] = [
  {
    id: '1',
    name: 'Media Office',
    description: 'Video editing software and computer area.',
    type: 'Room',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: true,
  },
  {
    id: '2',
    name: '3D Printer 1',
    description: 'Large 3D printer',
    type: 'Printer',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: false,
  },
  {
    id: '3',
    name: 'Occulus Rift Headset',
    description: 'Augmented reality headset and controllers',
    type: 'AR',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: true,
  },
  {
    id: '4',
    name: 'Meeting Space',
    description: '10 seating office meeting room. With whiteboards and TV screen.',
    type: 'Room',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: true,
  },
  {
    id: '5',
    name: '3D Printer 2',
    description: 'Medium 3D printer',
    type: 'Printer',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: true,
  },
  {
    id: '6',
    name: '3D Printer 3',
    description: 'Small 3D printer',
    type: 'Printer',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: true,
  },
  {
    id: '7',
    name: 'Raspberry Pi 1',
    description: 'Model 4 micro computer',
    type: 'Computer',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: false,
  },
  {
    id: '8',
    name: 'Raspberry Pi 2',
    description: 'Model 4 micro computer',
    type: 'Computer',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: true,
  },
  {
    id: '9',
    name: 'Raspberry Pi 3',
    description: 'Model 4 micro computer',
    type: 'Computer',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: true,
  },
  {
    id: '10',
    name: 'Raspberry Pi 4',
    description: 'Model 4 micro computer',
    type: 'Computer',
    createdAt: new Date(),
    createdBy: { id: '1', fullName: 'Mike' },
    isAvailable: true,
  },
];
