# This is a basic workflow to help you get started with Actions

name: Build and Test Admin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [opened, synchronize]
    paths:
      - "apps/garage-admin/**"
      - "packages/**"
      - ".github/workflows/azure-static-web-apps-agreeable-moss-0c522ba03.yml"
      - ".github/workflows/build_test_admin_react.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14.17"
      - name: yarn build and test admin frontend
        env:
          REACT_APP_BACKEND_URL: "http://test"
        run: |
          yarn install
          yarn workspace @my-garage/garage-admin run build --if-present
          yarn workspace @my-garage/garage-admin run test
