name: Cypress End to End Testing
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Get code to run tests on
      - name: Checkout
        uses: actions/checkout@v2

      # Build docker-compose container with frontend, backend and mongodb, cache them correctly
      - name: Build docker-compose
        uses: cypress-io/github-action@v2
        with:
          build: docker-compose up --build -d
          runTests: false

      # Set-up mongodb with test data
      - name: Populate database with test data
        run: mongoimport --db=my-garage --collection=users --drop --file ./services/garage-backend/fixtures/users.json

      # Run cypress tests
      - name: Cypress run tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          wait-on: "http://localhost:8080"

      # If cypress tests fail will upload a screenshot of the error
      - name: Save failure screenshots artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Test run video was always captured, so this action uses "always()" condition
      - name: Save video artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      # Close the docker-compose container incase there are zombie processes left
      - name: Stop containers
        if: always()
        run: docker-compose down
