name: Cypress End to End Testing
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn workspace @my-garage/garage-admin run build --if-present
          start: |
            yarn start:backend
            yarn dev:admin
          wait-on: "http://localhost:8080"
        
